name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14" # use whatever node version your project requires
      - name: Install dependencies
        run: yarn install
      - name: Build and Deploy
        run: |
          cd apps/yourbank-ui
          yarn deploy
